container/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\TagController;


Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('rooms')->group(function() {
        Route::get('list', [RoomController::class, 'index'])->name('rooms.list');
        Route::get('create', [RoomController::class, 'create'])->name('rooms.create');
        Route::post('store', [RoomController::class, 'store'])->name('rooms.store');
        Route::get('edit/{room_id}', [RoomController::class, 'edit'])->name('rooms.edit');
        Route::post('update/{id}', [RoomController::class, 'update'])->name('rooms.update');
        Route::delete('destroy/{id}', [RoomController::class, 'destroy'])->name('rooms.destroy');
        Route::get('show/{room_id}', [RoomController::class, 'show'])->name('rooms.show');
        Route::get('available-rooms', [RoomController::class, 'get_available_rooms'])->name('rooms.available_rooms');
        Route::get('unavailable-rooms', [RoomController::class, 'get_unavailable_rooms'])->name('rooms.unavailable_rooms');
    });

    Route::prefix('products')->group(function () {
        Route::get('list', [ProductController::class, 'index'])->name('products.list');
        Route::get('create', [ProductController::class, 'create'])->name('products.create');
        Route::post('store', [ProductController::class, 'store'])->name('products.store');
        Route::get('edit/{product_id}', [ProductController::class, 'edit'])->name('products.edit');
        Route::post('update/{id}', [ProductController::class, 'update'])->name('products.update');
        Route::delete('destroy/{id}', [ProductController::class, 'destroy'])->name('products.destroy');
        Route::get('show/{product_id}', [ProductController::class, 'show'])->name('products.show');
    });

    Route::prefix('clients')->group(function () {
        Route::get('list', [ClientController::class, 'index'])->name('clients.list');
        Route::get('create', [ClientController::class, 'create'])->name('clients.create');
        Route::post('store', [ClientController::class, 'store'])->name('clients.store');
        Route::get('edit/{client_id}', [ClientController::class, 'edit'])->name('clients.edit');
        Route::post('update', [ClientController::class, 'update'])->name('clients.update');
        Route::delete('destroy/{id}', [ClientController::class, 'destroy'])->name('clients.destroy');
        Route::get('show/{client_id}', [ClientController::class, 'show'])->name('clients.show');
    });

    Route::prefix('bookings')->group(function () {
        Route::get('list', [BookingController::class, 'index'])->name('bookings.list');
        Route::get('create', [BookingController::class, 'create'])->name('bookings.create');
        Route::post('store', [BookingController::class, 'store'])->name('bookings.store');
        Route::get('edit/{booking_id}', [BookingController::class, 'edit'])->name('bookings.edit');
        Route::post('update/{id}', [BookingController::class, 'update'])->name('bookings.update');
        Route::delete('destroy/{id}', [BookingController::class, 'destroy'])->name('bookings.destroy');
        Route::get('show/{booking_id}', [BookingController::class, 'show'])->name('bookings.show');
    });

    Route::prefix('orders')->group(function () {
        Route::get('list', [OrderController::class, 'index'])->name('orders.list');
        Route::get('create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('store', [OrderController::class, 'store'])->name('orders.store');
        Route::get('edit/{id}', [OrderController::class, 'edit'])->name('orders.edit');
        Route::post('update/{id}', [OrderController::class, 'update'])->name('orders.update');
        Route::delete('destroy/{id}', [OrderController::class, 'destroy'])->name('orders.destroy');
        Route::get('show/{booking_id}', [OrderController::class, 'show'])->name('orders.show');
    });

    Route::prefix('tags')->group(function () {
        Route::get('list', [TagController::class, 'index'])->name('tags.list');
        Route::get('create', [TagController::class, 'create'])->name('tags.create');
        Route::post('store', [TagController::class, 'store'])->name('tags.store');
        Route::get('edit/{id}', [TagController::class, 'edit'])->name('tags.edit');
        Route::post('update/{id}', [TagController::class, 'update'])->name('tags.update');
        Route::delete('destroy/{id}', [TagController::class, 'destroy'])->name('tags.destroy');
        Route::get('show/{id}', [TagController::class, 'show'])->name('tags.show');
    });


});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');

container/app/Models/Booking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Booking extends Model {
    use HasFactory;

    protected $fillable = ["client_id", "room_id", "checkin", "checkout"];

    public function clients() {
        return $this->belongsToMany(Client::class, 'bookings','id');
    }

    public function rooms() {
        return $this->belongsToMany(Room::class,'bookings','id');
    }

    public function getFormatedCreatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['created_at']));
    }

    public function getFormatedUpdatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['updated_at']));
    }

    public function getFormatedDeletedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['deleted_at']));
    }

    public function getFormatedCheckinAttribute() {
        return date("d/m/Y", strtotime($this->attributes['checkin']));
    }

    public function getFormatedCheckoutAttribute() {
        return date("d/m/Y", strtotime($this->attributes['checkout']));
    }

     public function getClientAttribute() {
         return Client::findOrFail($this->attributes['client_id']);
     }

      public function getRoomAttribute() {
          return Room::findOrFail($this->attributes['room_id']);
      }
}

container/app/Models/Client.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Client extends Model {
    use HasFactory;


    protected $fillable = ["name", "phone", "email", "birth", "cpf"];

    public function bookings() {
        return $this->hasMany(Booking::class);
    }

    public function payments() {
        return $this->hasMany(Payment::class);
    }

    public function orderClient() {
        return $this->belongsToMany(OrderClient::class);
    }

    public function getFormatedBirthAttribute() {
        return date("d/m/Y", strtotime($this->attributes['birth']));
    }

    public function getFormatedCreatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['created_at']));
    }

    public function getFormatedUpdatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['updated_at']));
    }

    public function getFormatedDeletedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['deleted_at']));
    }

    public function getFormatedNameAttribute() {
        return ucwords(mb_strtolower($this->attributes['name'], 'UTF-8'));
    }
}

container/app/Models/Room.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Room extends Model {
    use HasFactory;

    protected $fillable = ["description", "number", "status"];

    public function orders() {
        return $this->hasMany(Order::class);
    }

    public function bookings() {
        return $this->hasMany(Booking::class);
    }

    public function tags() {
        return $this->hasMany(Tag::class);
    }

    public function getFormatedCreatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['created_at']));
    }

    public function getFormatedUpdatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['updated_at']));
    }

    public function getFormatedDeletedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['deleted_at']));
    }

    public function getFormatedStatusAttribute() {
        return $this->attributes['status'] == true ? "Ocupado" : "Disponível";
    }

    public function getFormatedNumberAttribute() {
        return $this->attributes['number'];
    }

    public function getClientAttribute() {
        return Client::findOrFail($this->attributes['name']);
    }
}

container/app/Http/Controllers/BookingController.php
<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Models\Booking;
use App\Models\Client;
use App\Models\Room;

class BookingController extends Controller {
    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $bookings = Booking::with(['clients','rooms'])->get();
        return view('bookings.list', compact('bookings'));
    }

    public function create() {
        $clients = Client::all();
        $rooms   = Room::where('status', '=', 1)->get();
        return view('bookings.create', compact('clients', 'rooms'));
    }

    public function store(Request $request) {
        try {
            Booking::create($request->all());
            \Session::flash('flash_message', [
                'msg'   => 'Reserva cadastrada com sucesso!',
                'class' => 'alert-success'
            ]);
        } catch(PDOException $e) {
            \Session::flash('flash_message', [
                'msg'   => 'Ops, algo inesperado aconteceu...',
                'class' => 'alert-danger'
            ]);
        }
        return redirect()->route('bookings.list');
    }

    public function show($id) {
        $booking = Booking::find($id);
        if($booking) {
            return View('bookings.show', compact('booking'));
        } else {
            \Session::flash('flash_message', [
                'msg'   => 'Reserva não encontrada!',
                'class' => 'alert-danger'
            ]);
            return redirect()->route('bookings.list');
        }
    }

    public function edit($id) {
        $booking = Booking::findOrFail($id);
        $clients = Client::all();
        $rooms   = Room::all();
        if($booking) {
            return view('bookings.edit', compact('booking', 'clients', 'rooms'));
        } else {
            return redirect()->route('bookings.list');
        }
    }

    public function update(Request $request, $id) {
        try {
            $booking = Booking::findOrFail($id);
            $booking->update($request->all());
            \Session::flash('flash_message', [
                'msg'   => 'Quarto atualizado com sucesso!',
                'class' => 'alert-success'
            ]);
        } catch(PDOException $e) {
            \Session::flash('flash_message', [
                'msg'   => 'Ops, algo inesperado aconteceu...',
                'class' => 'alert-danger'
            ]);
        }
        return redirect()->route('bookings.list');
    }


    public function destroy($id)
    {
        try {
            Booking::findOrFail($id)->delete();
            return (['deleted' => true]);
        } catch (PDOException $e) {
            return Http::response('Erro - Não foi possível excluir', 500);
        }
    }
}

container/resources/views/bookings/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <h2 class="text-center">Fazer Reserva</h2>

    <form action="{{ route('bookings.store') }}" method="post">
        @csrf
        <div class="form-group row">
            <label for="client_id" class="col-md-4 col-form-label text-md-right">{{ __('Cliente') }}</label>
            <div class="col-md-6">
                <select name="client_id" id="client_id" class="custom-select-sm form-control @error('client_id') is-invalid @enderror" placeholder="Informe o Id do Cliente..." required autocomplete="client_id" autofocus>
                    @foreach($clients as $client)
                        <option value="{{ $client->id }}">{{ $client->formated_name }}</option>
                    @endforeach
                </select>
                @error('client_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="room_id" class="col-md-4 col-form-label text-md-right">{{ __('Quarto') }}</label>
            <div class="col-md-6">
                <select name="room_id" id="room_id" class="custom-select-sm form-control @error('room_id') is-invalid @enderror" placeholder="Informe o Id do Quarto..." required autocomplete="room_id" autofocus>
                    @foreach($rooms as $room)
                        <option value="{{ $room->id }}">Quanto número {{ $room->number }}</option>
                    @endforeach
                </select>
                @error('room_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="checkin" class="col-md-4 col-form-label text-md-right">{{ __('Entrada') }}</label>
            <div class="col-md-6">
                <input name="checkin" type="date" id="checkin" class="custom-select-sm form-control @error('checkin') is-invalid @enderror" placeholder="Informe a Data de Entrada..." required autocomplete="checkin" autofocus>
                @error('checkin')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>


        <div class="form-group row">
            <label for="checkout" class="col-md-4 col-form-label text-md-right">{{ __('Saída') }}</label>
            <div class="col-md-6">
                <input name="checkout" type="date" id="checkout" class="custom-select-sm form-control @error('checkout') is-invalid @enderror" placeholder="Informe a Data de Saída..." required autocomplete="checkout" autofocus>
                @error('checkout')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary m-1"><i class="fas fa-save p-1"></i>Salvar</button>
        </div>
    </form>
</div>
@endsection

container/resources/views/bookings/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <h2 class="text-center">Editar Reserva</h2>
    <form action="{{ route('bookings.update', $booking->id) }}" method="post">
        @csrf
        <div class="form-group row">
            <label for="client_id" class="col-md-4 col-form-label text-md-right">{{ __('Cliente') }}</label>
            <div class="col-md-6">
                <select name="client_id" id="client_id" class="custom-select-sm form-control @error('client_id') is-invalid @enderror" placeholder="Informe o Id do Cliente..." required autocomplete="client_id" autofocus>
                    <option value="{{ $booking->client_id }}" selected>{{ $booking->client->formated_name }}</option>
                    @foreach($clients as $client)
                        <option value="{{ $client->id }}">{{ $client->formated_name }}</option>
                    @endforeach
                </select>
                @error('client_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="room_id" class="col-md-4 col-form-label text-md-right">{{ __('Quarto') }}</label>
            <div class="col-md-6">
                <select name="room_id" id="room_id" class="custom-select-sm form-control @error('room_id') is-invalid @enderror" placeholder="Informe o Id do Cliente..." required autocomplete="room_id" autofocus>
                    <option value="{{ $booking->room_id }}" selected>Quarto N° {{ $booking->room->number }}</option>
                    @foreach($rooms as $room)
                        <option value="{{ $room->id }}">Quarto N° {{ $room->number }}</option>
                    @endforeach
                </select>
                @error('room_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="checkin" class="col-md-4 col-form-label text-md-right">{{ __('Data de Entrada') }}</label>
            <div class="col-md-6">
                <input name="checkin" type="date" id="checkin" value="{{ $booking->checkin }}" class="custom-select-sm form-control @error('checkin') is-invalid @enderror" placeholder="Informe a Data de Entrada..." required autocomplete="checkin" autofocus>
                @error('checkin')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="checkout" class="col-md-4 col-form-label text-md-right">{{ __('Data de Saída') }}</label>
            <div class="col-md-6">
                <input name="checkout" type="date" id="checkout" value="{{ $booking->checkout }}" class="custom-select-sm form-control @error('checkout') is-invalid @enderror" placeholder="Informe a Data de Saída..." required autocomplete="checkout" autofocus>
                @error('checkout')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="notes" class="col-md-4 col-form-label text-md-right">{{ __('Observação') }}</label>
            <div class="col-md-6">
                <input name="notes" type="text" id="notes" value="{{ $booking->notes }}" class="custom-select-sm form-control @error('notes') is-invalid @enderror" placeholder="Informe a Data de Saída..." required autocomplete="notes" autofocus>
                @error('notes')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>


        <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary"><i class="fas fa-save p-1"></i>Salvar</button>
        </div>
    </form>
</div>
@endsection

container/resources/views/bookings/list.blade.php
@extends('layouts.app')

@section('extra-styles')
    <style>
        td, th, tr {
            vertical-align: middle !important;
            text-align: center !important;
        }
    </style>
@endsection

@section('content')
<div class="container-fluid">
    <div class="text-center mb-3">
        <h2>Listagem de Reservas</h2>
    </div>
    <div class="table-responsive">
        <table class="table table-striped table-hover table-sm">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Cliente</th>
                    <th scope="col">Quarto</th>
                    <th scope="col">Entrada</th>
                    <th scope="col">Saída Prevista</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach($bookings as $booking)
                    <tr class="align-middle">
                        <td scope="row">{{ $booking->id }}</td>

                        <td>{{ $booking->client->formated_name }}</td>
                        <td>N° {{ $booking->room->formated_number }}</td>

                        <td>{{ $booking->formated_checkin }}</td>
                        <td>{{ $booking->formated_checkout }}</td>
                        <td class="d-flex justify-content-around">
                            <a href="{{ route('bookings.edit', $booking->id) }}" class="btn btn-sm btn-outline-secondary m-1"><i class="fas fa-pen"></i></a>
                            <a href="#" id="{{ 'del_' . $booking->id}}"  class="btn btn-sm btn-outline-danger m-1 delete"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection