container/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\TagController;


Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('rooms')->group(function() {
        Route::get('list', [RoomController::class, 'index'])->name('rooms.list');
        Route::get('create', [RoomController::class, 'create'])->name('rooms.create');
        Route::post('store', [RoomController::class, 'store'])->name('rooms.store');
        Route::get('edit/{room_id}', [RoomController::class, 'edit'])->name('rooms.edit');
        Route::post('update/{id}', [RoomController::class, 'update'])->name('rooms.update');
        Route::delete('destroy/{id}', [RoomController::class, 'destroy'])->name('rooms.destroy');
        Route::get('show/{room_id}', [RoomController::class, 'show'])->name('rooms.show');
        Route::get('available-rooms', [RoomController::class, 'get_available_rooms'])->name('rooms.available_rooms');
        Route::get('unavailable-rooms', [RoomController::class, 'get_unavailable_rooms'])->name('rooms.unavailable_rooms');
    });

    Route::prefix('products')->group(function () {
        Route::get('list', [ProductController::class, 'index'])->name('products.list');
        Route::get('create', [ProductController::class, 'create'])->name('products.create');
        Route::post('store', [ProductController::class, 'store'])->name('products.store');
        Route::get('edit/{product_id}', [ProductController::class, 'edit'])->name('products.edit');
        Route::post('update/{id}', [ProductController::class, 'update'])->name('products.update');
        Route::delete('destroy/{id}', [ProductController::class, 'destroy'])->name('products.destroy');
        Route::get('show/{product_id}', [ProductController::class, 'show'])->name('products.show');
    });

    Route::prefix('clients')->group(function () {
        Route::get('list', [ClientController::class, 'index'])->name('clients.list');
        Route::get('create', [ClientController::class, 'create'])->name('clients.create');
        Route::post('store', [ClientController::class, 'store'])->name('clients.store');
        Route::get('edit/{client_id}', [ClientController::class, 'edit'])->name('clients.edit');
        Route::post('update', [ClientController::class, 'update'])->name('clients.update');
        Route::delete('destroy/{id}', [ClientController::class, 'destroy'])->name('clients.destroy');
        Route::get('show/{client_id}', [ClientController::class, 'show'])->name('clients.show');
    });

    Route::prefix('bookings')->group(function () {
        Route::get('list', [BookingController::class, 'index'])->name('bookings.list');
        Route::get('create', [BookingController::class, 'create'])->name('bookings.create');
        Route::post('store', [BookingController::class, 'store'])->name('bookings.store');
        Route::get('edit/{booking_id}', [BookingController::class, 'edit'])->name('bookings.edit');
        Route::post('update/{id}', [BookingController::class, 'update'])->name('bookings.update');
        Route::delete('destroy/{id}', [BookingController::class, 'destroy'])->name('bookings.destroy');
        Route::get('show/{booking_id}', [BookingController::class, 'show'])->name('bookings.show');
    });

    Route::prefix('orders')->group(function () {
        Route::get('list', [OrderController::class, 'index'])->name('orders.list');
        Route::get('create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('store', [OrderController::class, 'store'])->name('orders.store');
        Route::get('edit/{id}', [OrderController::class, 'edit'])->name('orders.edit');
        Route::post('update/{id}', [OrderController::class, 'update'])->name('orders.update');
        Route::delete('destroy/{id}', [OrderController::class, 'destroy'])->name('orders.destroy');
        Route::get('show/{booking_id}', [OrderController::class, 'show'])->name('orders.show');
    });

    Route::prefix('tags')->group(function () {
        Route::get('list', [TagController::class, 'index'])->name('tags.list');
        Route::get('create', [TagController::class, 'create'])->name('tags.create');
        Route::post('store', [TagController::class, 'store'])->name('tags.store');
        Route::get('edit/{id}', [TagController::class, 'edit'])->name('tags.edit');
        Route::post('update/{id}', [TagController::class, 'update'])->name('tags.update');
        Route::delete('destroy/{id}', [TagController::class, 'destroy'])->name('tags.destroy');
        Route::get('show/{id}', [TagController::class, 'show'])->name('tags.show');
    });


});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');

container/app/Models/Client.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Client extends Model {
    use HasFactory;


    protected $fillable = ["name", "phone", "email", "birth", "cpf"];

    public function bookings() {
        return $this->hasMany(Booking::class);
    }

    public function payments() {
        return $this->hasMany(Payment::class);
    }

    public function orderClient() {
        return $this->belongsToMany(OrderClient::class);
    }

    public function getFormatedBirthAttribute() {
        return date("d/m/Y", strtotime($this->attributes['birth']));
    }

    public function getFormatedCreatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['created_at']));
    }

    public function getFormatedUpdatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['updated_at']));
    }

    public function getFormatedDeletedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['deleted_at']));
    }

    public function getFormatedNameAttribute() {
        return ucwords(mb_strtolower($this->attributes['name'], 'UTF-8'));
    }
}

container/app/Http/Controllers/ClientController.php
<?php
namespace App\Http\Controllers;
use App\Http\Requests\StoreClientRequest;
use App\Models\Client;

class ClientController extends Controller {
    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $clients = Client::all();
        return view('clients.list', compact('clients'));
    }

    public function create() {
        return view('clients.create');
    }

    public function store(StoreClientRequest $request) {
        try {
            Client::create($request->all());
            \Session::flash('flash_message', [
                'msg'   => 'Cliente cadastrado com sucesso!',
                'class' => 'alert-success'
            ]);
        } catch(PDOException $e) {
            \Session::flash('flash_message', [
                'msg'   => 'Ops, algo inesperado aconteceu...',
                'class' => 'alert-danger'
            ]);
        }
        return redirect()->route('clients.list');
    }

    public function show($id) {
        $client = Client::find($id);
        if($client) {
            return view('clients.show', compact('client'));
        } else {
            \Session::flash('flash_message', [
                'msg'   => 'Cliente não encontrado!',
                'class' => 'alert-danger'
            ]);
            return redirect()->route('clients.list');
        }
    }

    public function edit($id) {
        $client = Client::findOrFail($id);
        return view('clients.edit', compact('client'));
    }

    public function update(Request $request, $id) {
        $client = Client::findOrFail($id);
        try {
            $client->update($request->all());
            \Session::flash('flash_message', [
                'msg'   => 'Cliente atualizado com sucesso!',
                'class' => 'alert-success'
            ]);
        } catch(PDOException $e) {
            \Session::flash('flash_message', [
                'msg'   => 'Ops, algo inesperado aconteceu...',
                'class' => 'alert-danger'
            ]);
        }
        return redirect()->route('clients.list');
    }


    public function destroy($id)
    {
        try {
            Client::findOrFail($id)->delete();
            return (['deleted' => true]);
        } catch (PDOException $e) {
            return Http::response('Erro - Não foi possível excluir', 500);
        }
    }
}

container/resources/views/clients/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <h2 class="text-center">Cadastrar Cliente</h2>

    <form action="{{ route('clients.store') }}" method="post">
        @csrf
        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nome') }}</label>
            <div class="col-md-6">
                <input name="name" type="text" id="name" class="custom-select-sm form-control @error('name') is-invalid @enderror" placeholder="Informe o Nome..." required autocomplete="name" autofocus>
                @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Telefone') }}</label>
            <div class="col-md-6">
                <input name="phone" type="text" id="phone" class="custom-select-sm form-control @error('phone') is-invalid @enderror" placeholder="Informe o Telefone..." required autocomplete="phone" autofocus>
                @error('phone')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>
            <div class="col-md-6">
                <input name="email" type="text" id="email" class="custom-select-sm form-control @error('email') is-invalid @enderror" placeholder="Informe o E-Mail..." required autocomplete="email" autofocus>
                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="birth" class="col-md-4 col-form-label text-md-right">{{ __('Data de Nascimento') }}</label>
            <div class="col-md-6">
                <input name="birth" type="date" id="birth" class="custom-select-sm form-control @error('birth') is-invalid @enderror" placeholder="Informe a Data de Nascimento..." required autocomplete="birth" autofocus>
                @error('birth')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row align-moddle">
            <label for="cpf" class="col-md-4 col-form-label text-md-right">{{ __('CPF') }}</label>
            <div class="col-md-6">
                <input name="cpf" type="text" id="cpf" class="custom-select-sm form-control @error('cpf') is-invalid @enderror" placeholder="Informe o CPF..." required autocomplete="cpf" autofocus>
                @error('cpf')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary"><i class="fas fa-save p-1"></i>Salvar</button>
        </div>
    </form>
</div>
@endsection

container/resources/views/clients/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <h2 class="text-center">Editar Cliente</h2>
    <form action="" method="post">

        <div class="form-group row">
            <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Nome') }}</label>
            <div class="col-md-6">
                <input name="name" type="text" id="name" value="{{ $client->name }}" class="custom-select-sm form-control @error('name') is-invalid @enderror" placeholder="Informe o Nome..." required autocomplete="name" autofocus>
                @error('name')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="phone" class="col-md-4 col-form-label text-md-right">{{ __('Telefone') }}</label>
            <div class="col-md-6">
                <input name="phone" type="text" id="phone" value="{{ $client->phone }}" class="custom-select-sm form-control @error('phone') is-invalid @enderror" placeholder="Informe o Telefone..." required autocomplete="phone" autofocus>
                @error('phone')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail') }}</label>
            <div class="col-md-6">
                <input name="email" type="text" id="email" value="{{ $client->email }}" class="custom-select-sm form-control @error('email') is-invalid @enderror" placeholder="Informe o E-Mail..." required autocomplete="email" autofocus>
                @error('email')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="birth" class="col-md-4 col-form-label text-md-right">{{ __('Data de Nascimento') }}</label>
            <div class="col-md-6">
                <input name="birth" type="date" id="birth" value="{{ $client->birth }}" class="custom-select-sm form-control @error('birth') is-invalid @enderror" placeholder="Informe a Data de Nascimento..." required autocomplete="birth" autofocus>
                @error('birth')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row align-moddle">
            <label for="cpf" class="col-md-4 col-form-label text-md-right">{{ __('CPF') }}</label>
            <div class="col-md-6">
                <input name="cpf" type="text" id="cpf" value="{{ $client->cpf }}" class="custom-select-sm form-control @error('cpf') is-invalid @enderror" placeholder="Informe o CPF..." required autocomplete="cpf" autofocus>
                @error('cpf')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary"><i class="fas fa-save p-1"></i>Salvar</button>
        </div>
    </form>
</div>
@endsection

container/resources/views/clients/list.blade.php
@extends('layouts.app')

@section('extra-styles')
    <style>
        td, th, tr {
            vertical-align: middle !important;
            text-align: center !important;
        }
    </style>
@endsection

@section('content')
<div class="container-fluid">
    <div class="table-responsive">
        <div class="text-center mb-3">
            <h2>Listagem de Clients</h2>
        </div>
        <table class="table table-striped table-hover table-sm">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Nome</th>
                    <th scope="col">Telefone</th>
                    <th scope="col">Email</th>
                    <th scope="col">Data de Nascimento</th>
                    <th scope="col">CPF</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach($clients as $client)
                    <tr class="align-middle">
                        <td scope="row">{{ $client->id }}</td>
                        <td>{{ $client->name }}</td>
                        <td>{{ $client->phone }}</td>
                        <td>{{ $client->email }}</td>
                        <td>{{ $client->formated_birth }}</td>
                        <td>{{ $client->cpf }}</td>
                        <td class="d-flex justify-content-around">
                            <a href="{{ route('clients.edit', $client->id) }}" class="btn btn-sm btn-outline-secondary m-1"><i class="fas fa-pen"></i></a>
                            <a href="#" id="{{ 'del_' . $client->id}}"  class="btn btn-sm btn-outline-danger m-1 delete"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection


@section('extra-scripts')
<script>
window.onload = function() {
    $('.delete').click(function(e){
        let deletar = confirm('Deseja excluir este item?');

        if(deletar){
            let id = $(this).attr('id').split('_')[1];

            $.ajax({
                method: 'delete',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '/clients/destroy/' + id,
                success: function(res) {
                    alert('deletado com sucesso');
                    window.location.reload();
                },
                error: function(e) {
                    alert('erro ao excluir');
                }

            })
        }
    })
}
</script>
@endsection