container/routes/web.php
<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\RoomController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\BookingController;
use App\Http\Controllers\ProductController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\TagController;


Route::get('/', function () {
    return view('auth.login');
});

Route::middleware(['auth'])->group(function () {
    Route::prefix('rooms')->group(function() {
        Route::get('list', [RoomController::class, 'index'])->name('rooms.list');
        Route::get('create', [RoomController::class, 'create'])->name('rooms.create');
        Route::post('store', [RoomController::class, 'store'])->name('rooms.store');
        Route::get('edit/{room_id}', [RoomController::class, 'edit'])->name('rooms.edit');
        Route::post('update/{id}', [RoomController::class, 'update'])->name('rooms.update');
        Route::delete('destroy/{id}', [RoomController::class, 'destroy'])->name('rooms.destroy');
        Route::get('show/{room_id}', [RoomController::class, 'show'])->name('rooms.show');
        Route::get('available-rooms', [RoomController::class, 'get_available_rooms'])->name('rooms.available_rooms');
        Route::get('unavailable-rooms', [RoomController::class, 'get_unavailable_rooms'])->name('rooms.unavailable_rooms');
    });

    Route::prefix('products')->group(function () {
        Route::get('list', [ProductController::class, 'index'])->name('products.list');
        Route::get('create', [ProductController::class, 'create'])->name('products.create');
        Route::post('store', [ProductController::class, 'store'])->name('products.store');
        Route::get('edit/{product_id}', [ProductController::class, 'edit'])->name('products.edit');
        Route::post('update/{id}', [ProductController::class, 'update'])->name('products.update');
        Route::delete('destroy/{id}', [ProductController::class, 'destroy'])->name('products.destroy');
        Route::get('show/{product_id}', [ProductController::class, 'show'])->name('products.show');
    });

    Route::prefix('clients')->group(function () {
        Route::get('list', [ClientController::class, 'index'])->name('clients.list');
        Route::get('create', [ClientController::class, 'create'])->name('clients.create');
        Route::post('store', [ClientController::class, 'store'])->name('clients.store');
        Route::get('edit/{client_id}', [ClientController::class, 'edit'])->name('clients.edit');
        Route::post('update', [ClientController::class, 'update'])->name('clients.update');
        Route::delete('destroy/{id}', [ClientController::class, 'destroy'])->name('clients.destroy');
        Route::get('show/{client_id}', [ClientController::class, 'show'])->name('clients.show');
    });

    Route::prefix('bookings')->group(function () {
        Route::get('list', [BookingController::class, 'index'])->name('bookings.list');
        Route::get('create', [BookingController::class, 'create'])->name('bookings.create');
        Route::post('store', [BookingController::class, 'store'])->name('bookings.store');
        Route::get('edit/{booking_id}', [BookingController::class, 'edit'])->name('bookings.edit');
        Route::post('update/{id}', [BookingController::class, 'update'])->name('bookings.update');
        Route::delete('destroy/{id}', [BookingController::class, 'destroy'])->name('bookings.destroy');
        Route::get('show/{booking_id}', [BookingController::class, 'show'])->name('bookings.show');
    });

    Route::prefix('orders')->group(function () {
        Route::get('list', [OrderController::class, 'index'])->name('orders.list');
        Route::get('create', [OrderController::class, 'create'])->name('orders.create');
        Route::post('store', [OrderController::class, 'store'])->name('orders.store');
        Route::get('edit/{id}', [OrderController::class, 'edit'])->name('orders.edit');
        Route::post('update/{id}', [OrderController::class, 'update'])->name('orders.update');
        Route::delete('destroy/{id}', [OrderController::class, 'destroy'])->name('orders.destroy');
        Route::get('show/{booking_id}', [OrderController::class, 'show'])->name('orders.show');
    });

    Route::prefix('tags')->group(function () {
        Route::get('list', [TagController::class, 'index'])->name('tags.list');
        Route::get('create', [TagController::class, 'create'])->name('tags.create');
        Route::post('store', [TagController::class, 'store'])->name('tags.store');
        Route::get('edit/{id}', [TagController::class, 'edit'])->name('tags.edit');
        Route::post('update/{id}', [TagController::class, 'update'])->name('tags.update');
        Route::delete('destroy/{id}', [TagController::class, 'destroy'])->name('tags.destroy');
        Route::get('show/{id}', [TagController::class, 'show'])->name('tags.show');
    });


});

Auth::routes();
Route::get('/home', [HomeController::class, 'index'])->name('home');

container/app/Models/Order.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Order extends Model {
    use HasFactory;
    protected $table = 'orders';

    protected $fillable = ["product_id", "room_id", "status", "note"];

    public function products() {
        return $this->belongsToMany(Product::class);
    }

    public function rooms() {
        return $this->belongsTo(Room::class);
    }

    public function orderClient() {
        return $this->belongsToMany(OrderClient::class);
    }

    public function getFormatedCreatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['created_at']));
    }

    public function getFormatedUpdatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['updated_at']));
    }

    public function getFormatedDeletedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['deleted_at']));
    }

    public function getFormatedNotesAttribute() {
        if($this->attributes['notes'] == "")  {
            return "Sem Observações.";
        } else {
            return $this->attributes['notes'];
        }
    }

    public function getRoomAttribute() {
        return Room::findOrFail($this->attributes['room_id']);
    }

    public function getProductAttribute() {
        return Product::findOrFail($this->attributes['product_id']);
    }

    public function getFormatedStatusAttribute() {
        return $this->attributes['status'] == true ? "Finalizado" : "Em andamento";
    }
}

container/app/Models/Product.php
<?php
namespace App\Models;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;


class Product extends Model {
    use HasFactory;

    protected $fillable = ["product", "description", "price"];

    public function orders() {
        return $this->belongsToMany(Order::class);
    }

    public function getFormatedCreatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['created_at']));
    }

    public function getFormatedUpdatedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['updated_at']));
    }

    public function getFormatedDeletedAttribute() {
        return date("d/m/Y H:i:s", strtotime($this->attributes['deleted_at']));
    }

    public function getFormatedProductAttribute() {
        return $this->attributes['product'];
    }
}

container/app/Http/Controllers/OrderController.php
<?php
namespace App\Http\Controllers;
use App\Models\Order;
use App\Http\Requests\StoreOrderRequest;
use Illuminate\Http\Request;
use App\Models\Client;
use App\Models\Product;
use App\Models\Room;

class OrderController extends Controller {
    public function __construct() {
        $this->middleware('auth');
    }

    public function index() {
        $orders = Order::with('products')->get();
        return view('orders.list', compact('orders'));
    }

    public function create() {
        $rooms = Room::all();
        $products = Product::all();
        return view('orders.create', compact(['rooms','products']));
    }

    public function store(Request $request) {
        try {
            Order::create($request->all());
            \Session::flash('flash_message', [
                'msg'   => 'Produto criado com sucesso!',
                'class' => 'alert-success'
            ]);
        } catch(PDOException $e) {
            \Session::flash('flash_message', [
                'msg'   => 'Ops, algo inesperado aconteceu...',
                'class' => 'alert-danger'
            ]);
        }
        return redirect()->route('orders.list');
    }

    public function show($id) {
        $order  = Order::find($id);
        $room = Client::findOrFail($order->room_id);
        if($order) {
            return view('orders.show', compact('order'));
        } else {
            \Session::flash('flash_message', [
                'msg'   => 'Pedido não encontrad!',
                'class' => 'alert-danger'
            ]);
            return redirect()->route('orders.list');
        }
    }

    public function edit($id) {
        $order = Order::findOrFail($id);
        if($order) {
            return View('orders.edit', compact('room'));
        } else {
            return redirect()->route('orders.list');
        }
    }

    public function update(Request $request, $id) {
        try {
            $order = Order::findOrFail($id);
            $order->update($request->all());
            \Session::flash('flash_message', [
                'msg'   => 'Quarto atualizado com sucesso!',
                'class' => 'alert-success'
            ]);
        } catch(PDOException $e) {
            \Session::flash('flash_message', [
                'msg'   => 'Ops, algo inesperado aconteceu...',
                'class' => 'alert-danger'
            ]);
        }
        return redirect()->route('orders.list');
    }



    public function destroy($id) {
        try {
            Order::findOrFail($id)->delete();
            return(['deleted' => true]);

        } catch(PDOException $e) {
            return Http::response('Erro - Não foi possível excluir', 500);
        }
    }
}

container/resources/views/orders/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <h2 class="text-center">Adicionar Pedido</h2>

    <form action="{{ route('orders.store')}}" method="post">
        @csrf
        <div class="form-group row">
            <label for="product_id" class="col-md-4 col-form-label text-md-right">{{ __('Produto') }}</label>
            <div class="col-md-6">
                <select name="product_id" id="product_id" class="custom-select-sm form-control @error('product_id') is-invalid @enderror" placeholder="Informe o Id do Quarto..." required autocomplete="product_id" autofocus>
                    @foreach($products as $product)
                        <option value="{{ $product->id }}">{{ $product->product }}</option>
                    @endforeach
                </select>
                @error('product_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="room_id" class="col-md-4 col-form-label text-md-right">{{ __('Quarto') }}</label>
            <div class="col-md-6">
                <select name="room_id" id="room_id" class="custom-select-sm form-control @error('room_id') is-invalid @enderror" placeholder="Informe o Id do Quarto..." required autocomplete="room_id" autofocus>
                    @foreach($rooms as $room)
                        <option value="{{ $room->id }}">Quarto número {{ $room->number }}</option>
                    @endforeach
                </select>
                @error('room_id')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="room_id" class="col-md-4 col-form-label text-md-right">{{ __('Observações') }}</label>
            <div class="col-md-6">
                <input type="text" class="form-control" name="note" required/>

            </div>
        </div>

        <input type="hidden" name="status" value="1">
        <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary m-1"><i class="fas fa-save p-1"></i>Salvar</button>
        </div>
    </form>
</div>
@endsection

container/resources/views/orders/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <h2 class="text-center">Editar Pedido</h2>
    <form action="" method="post">

        <div class="form-group row">
            <label for="product" class="col-md-4 col-form-label text-md-right">{{ __('Produto') }}</label>
            <div class="col-md-6">
                <input name="product" type="text" id="product" value="{{ $product->product }}" class="custom-select-sm form-control @error('product') is-invalid @enderror" placeholder="Informe o Produto..." required autocomplete="product" autofocus>
                @error('product')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="form-group row">
            <label for="room" class="col-md-4 col-form-label text-md-right">{{ __('Quarto') }}</label>
            <div class="col-md-6">
                <input name="room" type="text" id="room" value="{{ $product->room }}" class="custom-select-sm form-control @error('description') is-invalid @enderror" placeholder="Informe a Descrição..." required autocomplete="description" autofocus>
                @error('description')
                    <span class="invalid-feedback" role="alert">
                        <strong>{{ $message }}</strong>
                    </span>
                @enderror
            </div>
        </div>

        <div class="text-center">
            <button type="submit" class="btn btn-sm btn-outline-primary m-1"><i class="fas fa-save p-1"></i>Salvar</button>
        </div>
    </form>
</div>
@endsection

container/resources/views/orders/list.blade.php
@extends('layouts.app')

@section('extra-styles')
    <style>
        td, th, tr {
            vertical-align: middle !important;
            text-align: center !important;
        }
    </style>
@endsection

@section('content')
<div class="container-fluid">
    <div class="table-responsive">
        <div class="text-center mb-3">
            <h2>Listagem de Pedidos</h2>
        </div>
        <table class="table table-striped table-hover table-sm">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Quarto</th>
                    <th scope="col">Produto</th>
                    <th scope="col">Status</th>
                    <th scope="col">Observações</th>
                    <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $order)
                    <tr class="align-middle">
                        <td scope="row">{{ $order->id }}</td>
                        <td>N° {{ $order->room->number }}</td>
                        <td>{{ $order->product->formated_product }}</td>
                        <td>{{ $order->formated_status }}</td>
                        <td>{{ $order->formated_notes }}</td>
                        <td class="d-flex justify-content-around">
                            <a href="{{ route('orders.edit', $order->id) }}" class="btn btn-sm btn-outline-secondary m-1"><i class="fas fa-pen"></i></a>
                            <a href="#" id="{{ 'del_' . $order->id}}"  class="btn btn-sm btn-outline-danger m-1 delete"><i class="fas fa-trash"></i></a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

@section('extra-scripts')
<script>
window.onload = function() {
    $('.delete').click(function(e){
        let deletar = confirm('Deseja excluir este item?');

        if(deletar){
            let id = $(this).attr('id').split('_')[1];

            $.ajax({
                method: 'delete',
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                },
                url: '/orders/destroy/' + id,
                success: function(res) {
                    alert('deletado com sucesso');
                    window.location.reload();
                },
                error: function(e) {
                    alert('erro ao excluir');
                }

            })
        }
    })
}
</script>
@endsection